apiVersion: v1
kind: Service
metadata:
  name: dns-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
  labels:
    k8s-app: kube-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    k8s-app: kube-dns
