kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
    - name: local-google
      image: alpine
      volumeMounts:
      - mountPath: "/data"
        name: csi-hw-volume
  volumes:
    - name: csi-hw-volume
      persistentVolumeClaim:
        claimName: storage-pvc
