apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    nodePort: 32062
    targetPort: http
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus  
